[package]
name = "logos-chat"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
# Workspace dependencies (sorted)
components = { workspace = true }
crossbeam-channel = { workspace = true }
embedded-logos-delivery = { workspace = true }
libchat = { workspace = true }
logos-generic-chat = { workspace = true }
