[package]
name = "embedded-logos-delivery"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
# Workspace dependencies (sorted)
crossbeam-channel = { workspace = true }
libchat = { workspace = true }
logos-delivery = { workspace = true }
logos-generic-chat = { workspace = true }

# External dependencies (sorted)
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"
